public class Sq {
   public final int cfT;
   public final int cfU;
   public final float cfV;
   public final int cfW;
   public final float cfX;
   public final float cfY;
   public final int cfZ;
   public final int cga;
   public final int cgb;
   public final int cgc;
   public final int cgd;
   public final int cge;
   public final int cgf;
   public final int cgg;
   public final int cgh;
   public final boolean cgi;
   public final int cgj;
   public final float cgk;
   public final int cgl;
   public final boolean cgm;
   public final boolean cgn;
   public final int cgo;
   public final boolean cgp;
   public final float cgq;
   public final int cgr;
   public final int cgs;
   public final int cgt;
   public final int cgu;
   public final int cgv;
   public final float cgw;
   public final int cgx;
   public final int cgy;
   public final int cgz;
   public final int cgA;
   public final int cgB;
   public final int cgC;
   public final int cgD;
   public final float cgE;
   public final boolean cgF;
   public final int cgG;
   public final boolean cgH;
   public final int cgI;
   public final int cgJ;
   public final int cgK;
   public final float cgL;
   public final int cgM;
   public final int cgN;
   public final float cgO;
   public final int cgP;
   public final boolean cgQ;
   public final int cgR;
   public final float cgS;
   public final boolean cgT;
   public final int cgU;
   public final int cgV;
   public final int cgW;
   public final int cgX;
   public final int cgY;
   public final int cgZ;
   public final int cha;
   public final float chb;
   public final float chc;
   public final float chd;
   public final boolean che;
   public final int chf;
   public final int chg;
   public final int chh;
   public final float chi;
   public final int chj;
   public final boolean chk;
   public final float chl;
   public final int chm;
   public final boolean chn;
   public final int cho;
   public final int chp;
   public final int chq;
   public final int chr;
   public final float chs;

   private Sq(Ss var1) {
      this.chs = var1.chs;
      this.chc = var1.chc;
      this.cfX = var1.cfX;
      this.chb = var1.chb;
      this.chd = var1.chd;
      this.cgE = var1.cgE;
      this.cgL = var1.cgL;
      this.cgS = var1.cgS;
      this.cgw = var1.cgw;
      this.cfY = var1.cfY;
      this.cfV = var1.cfV;
      this.chi = var1.chi;
      this.cgO = var1.cgO;
      this.chl = var1.chu;
      this.cgk = var1.cgk;
      this.cgq = var1.cgq;
      this.cgj = var1.bXp;
      this.cgT = var1.cgT;
      this.chn = var1.chn;
      this.cgC = var1.cgC;
      this.cgn = var1.cgn;
      this.cgm = var1.cgm;
      this.cgQ = var1.cgQ;
      this.chk = var1.chk;
      this.cgp = var1.cgp;
      this.cgF = var1.cgF;
      this.che = var1.che;
      this.cgc = var1.cgc;
      this.cgH = var1.cgH;
      this.cgK = var1.cgK;
      this.cgi = var1.cgi;
      this.cgD = var1.cgD;
      this.cgR = var1.cgR;
      this.cgW = var1.cgW;
      this.cgy = var1.cgy;
      this.cgZ = var1.cgZ;
      this.cgJ = var1.cgJ;
      this.cgU = var1.cgU;
      this.cho = var1.cho;
      this.cgM = var1.cgM;
      this.chf = var1.chf;
      this.cgV = var1.cgV;
      this.chp = var1.chp;
      this.cgo = var1.cgo;
      this.cgN = var1.cgN;
      this.cgY = var1.cgY;
      this.chh = var1.chh;
      this.cgA = var1.cgA;
      this.cfT = var1.cfT;
      this.cgB = var1.cgB;
      this.cgh = var1.cgh;
      this.cgb = var1.cgb;
      this.cgt = var1.cgt;
      this.cgg = var1.cgg;
      this.cgz = var1.cgz;
      this.cgl = var1.cgl;
      this.cgd = var1.cgd;
      this.cfZ = var1.cfZ;
      this.cgI = var1.cgI;
      this.chq = var1.chq;
      this.cgP = var1.cgP;
      this.cga = var1.cga;
      this.cgs = var1.cgs;
      this.cgu = var1.cgu;
      this.cgr = var1.cgr;
      this.cfW = var1.cfW;
      this.chr = var1.chr;
      this.chg = var1.chg;
      this.cfU = var1.cfU;
      this.cgG = var1.cgG;
      this.cgx = var1.cgx;
      this.cgf = var1.cgf;
      this.chm = var1.chm;
      this.cgX = var1.cgX;
      this.cge = var1.cge;
      this.cha = var1.cha;
      this.cgv = var1.cgv;
      this.chj = var1.chj;
   }
}
